projects:
  gfaTrainingData:
    schemaPath: amplify/backend/api/gfaTrainingData/build/schema.graphql
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: graphql
        region: eu-west-1
        apiId: null
        maxDepth: 2
